# Generated by Django 3.0.3 on 2020-04-03 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default='X', max_length=20)),
                ('collection_site', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3')], default='1', max_length=20)),
                ('collection_protocol', models.CharField(choices=[('1', 'P1'), ('2', 'P2'), ('3', 'P3')], default='1', max_length=50)),
                ('processing_protocol', models.CharField(choices=[('1', 'P1'), ('2', 'P2'), ('3', 'P3')], default='1', max_length=50)),
                ('technician', models.CharField(default='X', max_length=20)),
                ('lab', models.CharField(default='X', max_length=20)),
                ('institute', models.CharField(default='X', max_length=20)),
                ('collection_date', models.DateField(default=datetime.date.today, max_length=20)),
                ('processing_date', models.DateField(default=datetime.date.today, max_length=20)),
                ('machine_model', models.CharField(default='M1', max_length=20)),
                ('reagents', models.CharField(default='R1, R2, R3', max_length=100)),
                ('plate_id', models.CharField(default='X', max_length=15)),
                ('well', models.CharField(default='X', max_length=15)),
                ('pcr_results_csv', models.FileField(upload_to='documents/')),
                ('pcr_platemap_csv', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AddIndex(
            model_name='test_results',
            index=models.Index(fields=['barcode', 'collection_site', 'technician'], name='qpcr_record_barcode_5ac734_idx'),
        ),
    ]
