# Generated by Django 3.0.3 on 2020-04-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpcr_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='test_results',
            name='qpcr_record_barcode_5ac734_idx',
        ),
        migrations.RenameField(
            model_name='test_results',
            old_name='collection_protocol',
            new_name='rna_extraction_protocol',
        ),
        migrations.RenameField(
            model_name='test_results',
            old_name='collection_date',
            new_name='sampling_date',
        ),
        migrations.RenameField(
            model_name='test_results',
            old_name='well',
            new_name='sampling_plate_well',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='collection_site',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='machine_model',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='processing_date',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='processing_protocol',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='reagents',
        ),
        migrations.AddField(
            model_name='test_results',
            name='qpcr_instrument',
            field=models.CharField(choices=[('1', 'BioRad CFX_384'), ('2', 'BioRad CFX_XXX')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='test_results',
            name='qpcr_n1_well',
            field=models.CharField(default='X', max_length=2),
        ),
        migrations.AddField(
            model_name='test_results',
            name='qpcr_n2_well',
            field=models.CharField(default='X', max_length=2),
        ),
        migrations.AddField(
            model_name='test_results',
            name='qpcr_rp_well',
            field=models.CharField(default='X', max_length=2),
        ),
        migrations.AddField(
            model_name='test_results',
            name='sample_box_number',
            field=models.CharField(default='X', max_length=20),
        ),
        migrations.AddField(
            model_name='test_results',
            name='sample_box_x_position',
            field=models.CharField(default='X', max_length=20),
        ),
        migrations.AddField(
            model_name='test_results',
            name='sample_box_y_position',
            field=models.CharField(default='X', max_length=20),
        ),
        migrations.AddIndex(
            model_name='test_results',
            index=models.Index(fields=['barcode', 'technician', 'sampling_date'], name='qpcr_record_barcode_2d683d_idx'),
        ),
    ]
