# Generated by Django 3.0.3 on 2020-04-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpcr_records', '0003_auto_20200403_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_results',
            name='pcr_platemap_csv',
        ),
        migrations.AddField(
            model_name='test_results',
            name='fake_name',
            field=models.CharField(default='X', max_length=30),
        ),
        migrations.AddField(
            model_name='test_results',
            name='n1_ct_value',
            field=models.CharField(default='X', max_length=20),
        ),
        migrations.AddField(
            model_name='test_results',
            name='n2_ct_value',
            field=models.CharField(default='X', max_length=20),
        ),
        migrations.AddField(
            model_name='test_results',
            name='rp_ct_value',
            field=models.CharField(default='X', max_length=20),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='pcr_results_csv',
            field=models.URLField(default='X', max_length=300),
        ),
    ]
