# Generated by Django 3.0.3 on 2020-04-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpcr_records', '0004_auto_20200404_1949'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='test_results',
            name='qpcr_record_barcode_2d683d_idx',
        ),
        migrations.RenameField(
            model_name='test_results',
            old_name='qpcr_n1_well',
            new_name='plate_1_well',
        ),
        migrations.RenameField(
            model_name='test_results',
            old_name='qpcr_n2_well',
            new_name='plate_2_well',
        ),
        migrations.RenameField(
            model_name='test_results',
            old_name='qpcr_rp_well',
            new_name='plate_3_well',
        ),
        migrations.RenameField(
            model_name='test_results',
            old_name='sampling_plate_well',
            new_name='plate_4_well',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='n1_ct_value',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='n2_ct_value',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='plate_id',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='qpcr_instrument',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='rp_ct_value',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='sample_box_number',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='sample_box_x_position',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='sample_box_y_position',
        ),
        migrations.AddField(
            model_name='test_results',
            name='ms2_ct_mean_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='ms2_ct_sd_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='ms2_ct_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='n_ct_mean_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='n_ct_sd_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='n_ct_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='orf1ab_ct_mean_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='orf1ab_ct_sd_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='orf1ab_ct_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='plate_1_id',
            field=models.CharField(default='X', help_text='Scan or Enter for 96-well Plate 1', max_length=15),
        ),
        migrations.AddField(
            model_name='test_results',
            name='plate_2_id',
            field=models.CharField(default='X', help_text='Scan or Enter Barcode of 96-well Storage Plate', max_length=15),
        ),
        migrations.AddField(
            model_name='test_results',
            name='plate_3_id',
            field=models.CharField(default='X', help_text='Scan or Enter Barcode of Elution Plate from KingFisher', max_length=15),
        ),
        migrations.AddField(
            model_name='test_results',
            name='plate_4_id',
            field=models.CharField(default='X', help_text='Scan or Enter Barcode of Arraying EpMotion 394 Well Plate', max_length=15),
        ),
        migrations.AddField(
            model_name='test_results',
            name='plate_5_id',
            field=models.CharField(default='X', help_text='Scan or Enter Barcode of qPCR back-up Plate', max_length=15),
        ),
        migrations.AddField(
            model_name='test_results',
            name='plate_5_well',
            field=models.CharField(default='X', max_length=5),
        ),
        migrations.AddField(
            model_name='test_results',
            name='plate_6_id',
            field=models.CharField(default='X', help_text='Scan or Enter Barcode of qPCR Reaction Plate', max_length=15),
        ),
        migrations.AddField(
            model_name='test_results',
            name='plate_6_well',
            field=models.CharField(default='X', max_length=5),
        ),
        migrations.AddField(
            model_name='test_results',
            name='s_ct_mean_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='s_ct_sd_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_results',
            name='s_ct_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='test_results',
            index=models.Index(fields=['barcode', 'technician', 'sampling_date', 'plate_1_id', 'plate_2_id', 'plate_3_id', 'plate_4_id', 'plate_5_id', 'plate_6_id'], name='qpcr_record_barcode_b3f268_idx'),
        ),
    ]
