# Generated by Django 2.1.1 on 2020-04-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpcr_records', '0006_auto_20200408_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_results',
            old_name='frz_id',
            new_name='knight_lab_frz_id',
        ),
        migrations.AddField(
            model_name='test_results',
            name='andersson_lab_frz_id',
            field=models.CharField(default='', help_text='Enter Sample Storage Freezer Number', max_length=15),
        ),
        migrations.AddField(
            model_name='test_results',
            name='laurent_lab_frz_id',
            field=models.CharField(default='', help_text='Enter RNA Storage Freezer Number', max_length=15),
        ),
        migrations.AddField(
            model_name='test_results',
            name='lrl_id',
            field=models.CharField(default='', help_text='Lysis Reagent Lot #', max_length=15),
        ),
        migrations.AddField(
            model_name='test_results',
            name='peter_rwp_id',
            field=models.CharField(default='', help_text='Scan or Enter Barcode of Thermocycler RNA Working Plate', max_length=15),
        ),
    ]
