# Generated by Django 3.0.5 on 2020-04-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpcr_records', '0009_auto_20200410_1407'),
        ('qpcr_records', '0007_auto_20200410_0606'),
    ]

    operations = [
    ]
