# Generated by Django 3.0.3 on 2020-04-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpcr_records', '0010_merge_20200411_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='personnel_list',
            fields=[
                ('technician_name', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('technician_lab', models.CharField(default='', max_length=20)),
                ('technician_institute', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='qpcr_technician',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='qpcr_technician_institute',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='qpcr_technician_lab',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='rna_extraction_technician',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='rna_extraction_technician_institute',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='rna_extraction_technician_lab',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='sample_extraction_technician1',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='sample_extraction_technician1_institute',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='sample_extraction_technician1_lab',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='sample_extraction_technician2',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='sample_extraction_technician2_institute',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='sample_extraction_technician2_lab',
        ),
        migrations.AddField(
            model_name='test_results',
            name='personnel1_andersen_lab',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='test_results',
            name='personnel2_andersen_lab',
            field=models.CharField(default='', help_text='Name of Assisting Technician', max_length=25),
        ),
        migrations.AddField(
            model_name='test_results',
            name='personnel_knight_lab',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='test_results',
            name='personnel_laurent_lab',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='test_results',
            name='qpcr_date',
            field=models.DateField(default='2020-04-11'),
        ),
        migrations.AddField(
            model_name='test_results',
            name='re_date',
            field=models.DateField(default='2020-04-11'),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='sample_release',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='sampling_date',
            field=models.DateField(default='2020-04-11'),
        ),
    ]
