# Generated by Django 3.0.3 on 2020-04-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpcr_records', '0007_auto_20200410_1652'),
        ('qpcr_records', '0011_auto_20200411_1532'),
    ]

    operations = [
    ]
