# Generated by Django 3.0.3 on 2020-04-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpcr_records', '0012_merge_20200411_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_results',
            name='qrp_id',
            field=models.CharField(default='', help_text='Scan or Enter Barcode of qRTPCR Reaction Plate (QRP)', max_length=15),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='qsp_id',
            field=models.CharField(default='', help_text='Scan or Enter Barcode of qPCR_Storage Plate (QSP)', max_length=15),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='rep_id',
            field=models.CharField(default='', help_text='Scan or Enter Barcode of RNA Elution Plate (REP)', max_length=15),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='rsp_id',
            field=models.CharField(default='', help_text='Scan or Enter Barcode of RNA Storage Plate (RSP)', max_length=15),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='rwp_id',
            field=models.CharField(default='', help_text='Scan or Enter Barcode of RNA Working Plate (RWP)', max_length=15),
        ),
    ]
