# Generated by Django 3.0.3 on 2020-04-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpcr_records', '0013_auto_20200411_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_results',
            name='qsp_id',
        ),
        migrations.RemoveField(
            model_name='test_results',
            name='qsp_well',
        ),
    ]
